version: '3.7'
services:
  connector:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_HOSTS=kafka:9092
      - ADAPTER_HOST=172.17.0.1:7878
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "input:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka:/kafka
