sudo: required

language: node_js
node_js:
  - 13

services:
  - docker

arch:
  - rpi
  - amd64

branches:
  only:
  - master

os:
  - linux
  - windows

cache:
  directories:
    - ./node_modules

#before_install:
#  - npm i -g npm

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose pull

script:
  - docker-compose build
  - npm install
  - npm run-script build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    allow_failure: true
    keep_history: true
    verbose: true
    local_dir: dist
    edge: true
    on:
      branch: master
  - provider: script
    script: bash ./docker/push.sh
    verbose: true
    on:
      branch: master
