os:
  - linux
dist: trusty
sudo: required

language: node_js
node_js:
  - 13

services:
  - docker

arch:
  - rpi
  - amd64

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm i -g npm
  - npm i -g @angular/cli

cache:
  directories:
    - ./server/node_modules
    - ./client/node_modules

jobs:
  include:
    - before_script:
        - docker build -f docker/server/test.Dockerfile -t strangesast/core_server_dev .
      script:
      - docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" strangesast/core_server_dev npm test
    - before_script:
      - cd ./client/
      - npm install
      script:
      - npm run-script lint
      - npm run-script test:ci
      - npm run-script e2e
      - npm run-script build:ci

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    allow_failure: true
    keep_history: true
    verbose: true
    local_dir: ./timeclock-vis/client/dist
    edge: true
    on:
      branch: master
  - provider: script
    script: docker-compose push
    verbose: true
    on:
      branch: master

branches:
  only:
  - master

cache:
  directories:
    - ./timeclock-vis/client/node_modules

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose build
  - cd ./client/
  - npm install
  - npm run-script build:ci
