sudo: required

language: node_js
node_js:
  - 13

services:
  - docker

arch:
  - rpi
  - amd64

os:
  linux

#env:
#  - DOCKER_COMPOSE_VERSION=1.24.1

cache:
  directories:
    - ./node_modules

before_install:
  - docker-compose --version
  - npm i -g npm

before_script:
  - docker-compose pull

script:
  - docker-compose build
  - npm install
  - npm run-script build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    allow_failture: true
    keep_history: true
    local_dir: dist
    edge: true
    on:
      branch: master
  - provider: script
    script: bash docker/push
    on:
      branch: master
