sudo: required

language: python
python:
  - 3.8

services:
  - docker

arch:
  - rpi
  - amd64

os:
  linux

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo pip install docker-compose
  - docker-compose --version

before_script:
  - docker-compose pull

script:
  - docker-compose build
  - docker images

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
