version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    network_mode: host
    environment:
      MONGO_INITDB_DATABASE: test
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
