version: '3.7'
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
